# Generated by Django 5.2.8 on 2025-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('specialty', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pbcatcol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbc_tnam', models.CharField(max_length=64)),
                ('pbc_tid', models.IntegerField(blank=True, null=True)),
                ('pbc_ownr', models.CharField(max_length=64)),
                ('pbc_cnam', models.CharField(max_length=64)),
                ('pbc_cid', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_labl', models.CharField(blank=True, max_length=254, null=True)),
                ('pbc_lpos', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_hdr', models.CharField(blank=True, max_length=254, null=True)),
                ('pbc_hpos', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_jtfy', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_mask', models.CharField(blank=True, max_length=31, null=True)),
                ('pbc_case', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_hght', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_wdth', models.SmallIntegerField(blank=True, null=True)),
                ('pbc_ptrn', models.CharField(blank=True, max_length=31, null=True)),
                ('pbc_bmap', models.CharField(blank=True, max_length=1, null=True)),
                ('pbc_init', models.CharField(blank=True, max_length=254, null=True)),
                ('pbc_cmnt', models.CharField(blank=True, max_length=254, null=True)),
                ('pbc_edit', models.CharField(blank=True, max_length=31, null=True)),
                ('pbc_tag', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'pbcatcol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pbcatedt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbe_name', models.CharField(max_length=30)),
                ('pbe_edit', models.CharField(blank=True, max_length=254, null=True)),
                ('pbe_type', models.SmallIntegerField(blank=True, null=True)),
                ('pbe_cntr', models.IntegerField(blank=True, null=True)),
                ('pbe_seqn', models.SmallIntegerField()),
                ('pbe_flag', models.IntegerField(blank=True, null=True)),
                ('pbe_work', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'pbcatedt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pbcatfmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbf_name', models.CharField(max_length=30, unique=True)),
                ('pbf_frmt', models.CharField(blank=True, max_length=254, null=True)),
                ('pbf_type', models.SmallIntegerField(blank=True, null=True)),
                ('pbf_cntr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pbcatfmt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pbcattbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbt_tnam', models.CharField(max_length=64)),
                ('pbt_tid', models.IntegerField(blank=True, null=True)),
                ('pbt_ownr', models.CharField(max_length=64)),
                ('pbd_fhgt', models.SmallIntegerField(blank=True, null=True)),
                ('pbd_fwgt', models.SmallIntegerField(blank=True, null=True)),
                ('pbd_fitl', models.CharField(blank=True, max_length=1, null=True)),
                ('pbd_funl', models.CharField(blank=True, max_length=1, null=True)),
                ('pbd_fchr', models.SmallIntegerField(blank=True, null=True)),
                ('pbd_fptc', models.SmallIntegerField(blank=True, null=True)),
                ('pbd_ffce', models.CharField(blank=True, max_length=18, null=True)),
                ('pbh_fhgt', models.SmallIntegerField(blank=True, null=True)),
                ('pbh_fwgt', models.SmallIntegerField(blank=True, null=True)),
                ('pbh_fitl', models.CharField(blank=True, max_length=1, null=True)),
                ('pbh_funl', models.CharField(blank=True, max_length=1, null=True)),
                ('pbh_fchr', models.SmallIntegerField(blank=True, null=True)),
                ('pbh_fptc', models.SmallIntegerField(blank=True, null=True)),
                ('pbh_ffce', models.CharField(blank=True, max_length=18, null=True)),
                ('pbl_fhgt', models.SmallIntegerField(blank=True, null=True)),
                ('pbl_fwgt', models.SmallIntegerField(blank=True, null=True)),
                ('pbl_fitl', models.CharField(blank=True, max_length=1, null=True)),
                ('pbl_funl', models.CharField(blank=True, max_length=1, null=True)),
                ('pbl_fchr', models.SmallIntegerField(blank=True, null=True)),
                ('pbl_fptc', models.SmallIntegerField(blank=True, null=True)),
                ('pbl_ffce', models.CharField(blank=True, max_length=18, null=True)),
                ('pbt_cmnt', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'pbcattbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pbcatvld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbv_name', models.CharField(max_length=30, unique=True)),
                ('pbv_vald', models.CharField(blank=True, max_length=254, null=True)),
                ('pbv_type', models.SmallIntegerField(blank=True, null=True)),
                ('pbv_cntr', models.IntegerField(blank=True, null=True)),
                ('pbv_msg', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'pbcatvld',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_details', models.TextField()),
                ('prescription_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'managed': False,
            },
        ),
    ]
